chitchat/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_view
from .views import home_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_view,  name='home'),
    path('account/', include('accounts.urls', namespace='accounts')),
    path('profiles/', include('profiles.urls', namespace='profiles'), name='profiles'),
    path('posts/', include('posts.urls', namespace='posts'), name='posts'),
    path('login/', auth_view.LoginView.as_view(), name='login'),
    path('logout/', auth_view.LogoutView.as_view(), name='logout')
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

posts/urls.py
from django.urls import path
from .views import post_comment_create_and_list_view, like_unlike_post, PostDeleteView, PostUpdateView

app_name = 'posts'

urlpatterns =[
    path('', post_comment_create_and_list_view, name='main_post_view'),
    path('like/', like_unlike_post, name='like_post_view'),
    path('<pk>/delete', PostDeleteView.as_view(), name='post_delete'),
    path('<pk>/update', PostUpdateView.as_view(), name='post_update')
]

profiles/urls.py
from django.urls import path
from .views import my_profile_view, invite_received_view, profile_list_view, profiles_i_can_invite, ProfileDetailView, ProfileListView, send_invitation, remove_from_friends, accept_invitation, reject_invitation

app_name = 'profiles'

urlpatterns = [
    path('', ProfileListView.as_view(), name='all_profiles'),
    path('myprofile/', my_profile_view, name='my_profile_view'),
    path('invites/', invite_received_view, name='invites'),
    path('invite_friends/', profiles_i_can_invite, name='invite_friends'),
    path('send-invite/', send_invitation, name='send-invite'),
    path('remove-friend/', remove_from_friends, name='remove-friend'),
    path('<slug>/', ProfileDetailView.as_view(), name='profile_detail_view'),
    path('invites/accept_invite', accept_invitation, name='accept_invite'),
    path('invites/reject_invite/', reject_invitation, name='reject_invite'),

]

profiles/models.py
from django.db import models
from django.shortcuts import reverse
from django.contrib.auth.models import User
from .utils import get_random_code
from django.template.defaultfilters import slugify
from django.db.models import Q
from cloudinary.models import CloudinaryField


# Create your models here.

class ProfileManager(models.Manager):

    def get_all_profiles_to_invite(self, sender):
        profiles = Profile.objects.all().exclude(user=sender)
        myprofile = Profile.objects.get(user=sender)
        query = Relationship.objects.filter(Q(sender=myprofile) | Q(receiver=myprofile))

        accepted = []
        for rel in query:
            if rel.status == 'accepted':
                accepted.append(rel.receiver)
                accepted.append(rel.sender)
        print(accepted)

        available = [profile for profile in profiles if profile not in accepted]
        print(available)
        return available

    def get_all_profiles(self, me):
        profiles = Profile.objects.all().exclude(user=me)
        return profiles


class Profile(models.Model):
    first_name = models.CharField(max_length=200, blank=True)
    last_name = models.CharField(max_length=200, blank=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(default="no bio...", max_length=300, verbose_name='bio')
    DOB = models.DateField(verbose_name='Date of Birth', blank=True, null=True)
    email = models.EmailField(max_length=200, blank=True, verbose_name='email')
    address = models.CharField(max_length=300, blank=True, verbose_name='address')
    phone_number = models.CharField(max_length=15, blank=True, verbose_name='phone number')
    country = models.CharField(max_length=200, blank=True)
    # avatar = models.ImageField(default='avatar.png', upload_to='avatars/')
    avatar = CloudinaryField('avatar', blank=True,)
    friends = models.ManyToManyField(User, blank=True, related_name='friends')
    slug = models.SlugField(unique=True, blank=True)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    objects = ProfileManager()

    def __str__(self):
        return f"{self.user.username}-{self.created.strftime('%d-%m-%Y')}"

    def get_absolute_url(self):
        return reverse("profiles:profile_detail_view", kwargs={"slug": self.slug})

    def get_friends(self):
        return self.friends.all()

    def get_friends_number(self):
        return self.friends.all().count()

    def get_posts_no(self):
        return self.posts.all().count()

    def get_all_authors_posts(self):
        return self.posts.all()

    def get_likes_given_no(self):
        likes = self.like_set.all()
        total_liked = 0
        for item in likes:
            if item.value == 'Like':
                total_liked += 1
        return total_liked

    def get_likes_received(self):
        posts = self.posts.all()
        total_liked = 0
        for item in posts:
            total_liked += item.liked.all().count()
        return total_liked

    __initial_first_name = None
    __initial_last_name = None

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.__initial_first_name = self.first_name
        self.__initial_last_name = self.last_name

    def save(self, *args, **kwargs):
        ex = False
        to_slug = self.slug
        if self.first_name != self.__initial_first_name or self.last_name != self.__initial_last_name or self.slug == "":
            if self.first_name and self.last_name:
                to_slug = slugify(str(self.first_name) + " " + str(self.last_name))
                ex = Profile.objects.filter(slug=to_slug).exists()
                while ex:
                    to_slug = slugify(to_slug + " " + str(get_random_code()))
                    ex = Profile.objects.filter(slug=to_slug).exists()

            else:
                to_slug = str(self.user)
        self.slug = to_slug
        super().save(*args, **kwargs)


STATUS_CHOICES = (
    ('send', 'send'),
    ('accepted', 'accepted')
)


class RelationshipManager(models.Manager):
    def invitations_received(self, receiver):
        query_set = Relationship.objects.filter(receiver=receiver, status='send')
        return query_set


class Relationship(models.Model):
    sender = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='sender')
    receiver = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='receiver')
    status = models.CharField(max_length=8, choices=STATUS_CHOICES)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    objects = RelationshipManager()

    def __str__(self):
        return f"{self.sender}-{self.receiver}-{self.status}"

profiles/forms.py
from django import forms
from .models import Profile


class ProfileModelForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('first_name', 'last_name', 'bio', 'address', 'phone_number', 'DOB', 'avatar')

profiles/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Profile, Relationship
from .forms import ProfileModelForm
from django.db.models import Q
from django.views.generic import ListView, DetailView
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required


# Create your views here.
@login_required(login_url="/login/")
def my_profile_view(request):
    # get profile of the current user
    profile = Profile.objects.get(user=request.user)
    form = ProfileModelForm(request.POST or None, request.FILES or None, instance=profile)
    confirm = False
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            confirm = True

    context = {
        'profile': profile,
        'form': form,
        'confirm': confirm,
    }
    return render(request, 'profile/myprofile.html', context)


def invite_received_view(request):
    profile = Profile.objects.get(user=request.user)
    query = Relationship.objects.invitations_received(profile)
    results = list(map(lambda x: x.sender, query))
    is_empty = False
    if len(results) == 0:
        is_empty = True
    context = {
        'query': results,
        'is_empty': is_empty,
    }
    return render(request, 'profile/invite.html', context)


def accept_invitation(request):
    if request.method == "POST":
        pk = request.POST.get('profile_pk')
        sender = Profile.objects.get(pk=pk)
        receiver = Profile.objects.get(user=request.user)
        rel = get_object_or_404(Relationship, sender=sender, receiver=receiver)
        if rel.status == 'send':
            rel.status = 'accepted'
            rel.save()
    return redirect('profiles:invites')


def reject_invitation(request):
    if request.method == "POST":
        pk = request.POST.get('profile_pk')
        sender = Profile.objects.get(pk=pk)
        receiver = Profile.objects.get(user=request.user)
        rel = get_object_or_404(Relationship, sender=sender, receiver=receiver)
        rel.delete()
    return redirect('profiles:invites')


# function based view for profile list
# @login_required(login_url="/login/")
def profile_list_view(request):
    user = request.user
    qs = Profile.objects.get_all_profiles(user)

    context = {
        'qs': qs,
    }

    return render(request, 'profiles/profile_list.html', context)


def profiles_i_can_invite(request):
    user = request.user
    query = Profile.objects.get_all_profiles_to_invite(user)

    context = {
        'query': query,
    }
    return render(request, 'profile/to_invite_list.html', context)


class ProfileDetailView(DetailView):
    model = Profile
    template_name = 'profile/detail.html'

    def get_object(self, slug=None):
        slug = self.kwargs.get('slug')
        profile = Profile.objects.get(slug=slug)
        return profile

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = User.objects.get(username__iexact=self.request.user)
        profile = Profile.objects.get(user=user)

        rel_r = Relationship.objects.filter(sender=profile)  # relationship where user is the sender
        rel_s = Relationship.objects.filter(receiver=profile)  # relationship where user is the receiver
        rel_receiver = []
        rel_sender = []
        for item in rel_r:
            rel_receiver.append(item.receiver.user)

        for item in rel_s:
            rel_sender.append(item.receiver.user)

        context["rel_receiver"] = rel_receiver
        context["rel_sender"] = rel_sender
        context['posts'] = self.get_object().get_all_authors_posts()
        context['len_posts'] = True if len(self.get_object().get_all_authors_posts()) > 0 else False

        return context


# class based view  for list of user profiles in the system
# @login_required(login_url="/login/")
class ProfileListView(ListView):
    model = Profile
    template_name = 'profile/profile_list.html'

    # context_object_name = 'qs'

    def get_queryset(self):
        qs = Profile.objects.get_all_profiles(self.request.user)
        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = User.objects.get(username__iexact=self.request.user)
        profile = Profile.objects.get(user=user)

        rel_r = Relationship.objects.filter(sender=profile)  # relationship where user is the sender
        rel_s = Relationship.objects.filter(receiver=profile)  # relationship where user is the receiver
        rel_receiver = []
        rel_sender = []
        for item in rel_r:
            rel_receiver.append(item.receiver.user)

        for item in rel_s:
            rel_sender.append(item.receiver.user)

        context["rel_receiver"] = rel_receiver
        context["rel_sender"] = rel_sender
        context["is_empty"] = False

        if len(self.get_queryset()) == 0:
            context["is_empty"] = True

        return context


@login_required(login_url="/login/")
def send_invitation(request):
    if request.method == 'POST':
        pk = request.POST.get('profile_pk')
        user = request.user
        sender = Profile.objects.get(user=user)
        receiver = Profile.objects.get(pk=pk)

        rel = Relationship.objects.create(sender=sender, receiver=receiver, status='send')

        return redirect(request.META.get('HTTP_REFERER'))
    return redirect('profiles:my_profile_view')


@login_required(login_url="/login/")
def remove_from_friends(request):
    if request.method == 'POST':
        pk = request.POST.get('profile_pk')
        user = request.user
        sender = Profile.objects.get(user=user)
        receiver = Profile.objects.get(pk=pk)

        rel = Relationship.objects.get(
            (Q(sender=sender) & Q(receiver=receiver)) | Q(sender=receiver) & (Q(receiver=sender))
        )
        rel.delete()
        return redirect(request.META.get('HTTP_REFERER'))
    return redirect('profiles:my_profile_view')

templates/profile/detail.html
{% extends 'base.html' %}

{% block title %}
    Profile Detail
{% endblock title %}

{% block content %}
<div class="ui grid">
    <br>
    <div class="row">
        <div class="four wide column">
            <img class="ui medium rounded image" src={{object.avatar.url}}>
            <h1>{{object.user}}</h1>
            <div class="ui vertical fluid menu">
                <div class="item">
                    Posts
                    <div class="ui label">{{object.get_posts_no}}</div>
                </div>
                <div class="item">
                    Likes Given
                    <div class="ui label">{{object.get_likes_given_no}}</div>
                </div>
                <div class="item">
                    Likes Received
                    <div class="ui label">{{object.get_likes_received}}</div>
                </div>
                <div class="item">
                    Friends
                    <div class="ui label">{{object.get_friends_number}}</div>
                </div>
                </div>


                {% if object.user not in rel_receiver and object.user not in rel_sender %}
                    <form action="{% url 'profiles:send-invite'%}" method="POST">
                        {% csrf_token%}
                        <input type="hidden" name="profile_pk" value="{{object.pk}}">
                        <button class="ui positive basic button mb-7, w_big"><i class="plus square icon"></i> Add to friend list </button>
                    </form>
                    {% endif %}

                    {% if object.user in rel_receiver and request.user not in object.friends.all%}
                        <p><i class="user icon"></i>Waiting for approval</p>
                    {% endif %}

                    {% if request.user in object.friends.all %}
                        <form action="{% url 'profiles:remove-friend'%}" method="POST">
                            {% csrf_token%}
                            <input type="hidden" name="profile_pk" value="{{object.pk}}">
                            <button class="ui negative basic button mb-7, w_big"><i class="minus square icon"></i> Remove from friend list </button>
                        </form>
                    {% endif %}

        </div>
        <div class="twelve wide column">
            {% if len_posts %}
                {% for post in posts %}
                    <div class="segment ui fluid">
                        {{post.content}}
                    </div>
                {% endfor %}
            {% else %}
                <h1>No post of this user...</h1>
            {% endif %}
        </div>
    </div>
</div>
{% endblock content %}

templates/profile/invite.html
{% extends 'base.html' %}

{% block title %} Friend Requests {% endblock title%}

{% block content %}

    {% if is_empty %}
        <h1>No invitations here...</h1>
    {% endif %}

    {% for obj in query %}
        <div class="ui segment">
            <div class="ui grid">
                <div class="row">
                    <div class="three wide column">
                        <img src="ui small circular image"src={{obj.avatar.url}}>
                    </div>
                    <div class="thirteen wide column">
                        <h3>{{obj.user }}</h3>
                        <p>{{obj.bio}}</p>
                        <a href="">
                            <button class="ui primary button w-big mb-7">View Profile</button>
                        </a>
                        <form action="{%url 'profiles:accept_invite' %}" method="POST">
                             {% csrf_token %}
                            <input type="hidden" name="profile_pk" value="{{obj.pk}}">
                            <button type="submit" class="ui positive basic button w-big mb-7">
                                <i class="check icon"></i>
                                Accept Invite
                            </button>
                        </form>
                        <form action="{% url 'profiles:reject_invite' %}" method="POST">
                             {% csrf_token %}
                            <input type="hidden" name="profile_pk" value="{{obj.pk}}">
                            <button type="submit" class="ui negative basic button w-big mb-7">
                                <i class="close icon"></i>
                                Reject Invite
                            </button>
                        </form>

                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
{% endblock content %}

templates/profile/myprofile.html
{% extends 'base.html'%} {% block title %} My Profile {% endblock title%} {% block content%}
<!--MODAL-->
<div class="ui modal">
    <i class="close icon"></i>
    <div class="header">
        Update your ChitChat profile
    </div>
    <div class="image content scrolling">
        <div class="ui medium image">
            <img src={{profile.avatar.url}}>
        </div>
        <div class="description">
            <div class="ui header">Provide additional info about yourself. Providing this makes it easier for your friend to find you</div>
            <form action="" method="POST" class="ui form" enctype="multipart/form-data">
                {% csrf_token %} {{form.as_p}}
            </form>
        </div>
    </div>
    <div class="actions">
        <button type="submit" class="ui positive right labeled icon button">
      Update
      <i class="checkmark icon"></i>
    </button>

    </div>
</div>
<!--MODAL-->
<div class="ui segment">
    {%if confirm %}
    <div class="ui teal message">Your profile has been updated <i class="checkmark icon"></i></div>
    {% endif %}
    <h3>profile: {{request.user}}</h3>
    <div class="ui grid">
        <div class="row">
            <div class="six wide column">
                {% if profile.avatar %}
                <img class="ui medium bordered circular image " src="{{profile.avatar.url}}" />
                {% else %}
                <img class="ui medium bordered circular image " src="../../../static_cdn/media_root/avatar.png" />
                {% endif %}
                <div id="mt-5" style="margin-top: 10px">
                    <button class="ui secondary button" id="modal-btn">Update your profile</button>
                </div>
            </div>
            <div class="ten wide column">
                <table class="ui table">
                    <tbody>
                        <tr>
                            <td>Username</td>
                            <td class="profile-detail" style="">{{profile.user}}</td>
                        </tr>
                        <tr>
                            <td>Last Name</td>
                            <td>{{profile.last_name}}</td>
                        </tr>
                        <tr>
                            <td>First Name</td>
                            <td>{{profile.first_name}}</td>
                        </tr>
                        <tr>
                            <td>Date of Birth</td>
                            <td>{{profile.DOB}}</td>
                        </tr>
                        <tr>
                            <td>Nationality</td>
                            <td>{{profile.country}}</td>
                        </tr>
                        <tr>
                            <td>Address</td>
                            <td>{{profile.address}}</td>
                        </tr>
                        <tr>
                            <td>Mobile Number</td>
                            <td>{{profile.phone_number}}</td>
                        </tr>
                        <tr>
                            <td>About Me</td>
                            <td>{{profile.bio}}</td>
                        </tr>
                        <tr>
                            <td>No of Friends</td>
                            <td>You have {{profile.get_friends_number}} friends</td>
                        </tr>
                        <tr>
                            <td>Friends</td>
                            <td>
                                <ul>
                                    {% for friend in profile.get_friends%}
                                    <li>{{friend}}</li>
                                    {%endfor%}
                                </ul>
                            </td>
                        </tr>
                        <tr>
                            <td>No of Posts</td>
                            <td>You have {{profile.get_posts_no}}</td>
                        </tr>
                        <tr>
                            <td>No of Likes</td>
                            <td>You have {{profile.get_likes_give}}</td>
                        </tr>
                        <tr>
                            <td>No of Likes Received</td>
                            <td>You have {{profile.get_likes_received}}</td>
                        </tr>

                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>


{% endblock content%}

templates/profile/navbar.html
<div class="ui inverted menu nav mb-7">
  <div class="ui container">
    <a href="{% url 'posts:main_post_view' %}" class="item">
        <h3>ChitChat</h3>
    </a>
    {% if request.user.is_authenticated %}
    <a href="{% url 'posts:main_post_view' %}" class="item">
        Home
    </a>
    {% endif %}

    <div class="right menu">
        {% if request.user.is_authenticated %}
        <div class="item">
            <div class="ui simple dropdown item teal"> Friends
                <i class="dropdown icon"></i>
                <div class="menu">
                    <a href="{% url 'profiles:all_profiles' %}" class="item">
                        All Profiles
                    </a>
                    <a href="{% url 'profiles:invite_friends' %}" class="item">
                        Send Invites
                    </a>
                    <a href="{% url 'profiles:invites' %}" class="item">
                        Received Invites
                    </a>
                </div>
             </div>
        </div>
             <div class="item">
              <form action="" method="GET">
                <div class="ui action left icon input">
                <input class="prompt" type="text" name='q' placeholder="name of a friend...">
                <i class="search icon"></i>
                <button type='submit' class="ui button">Search</button>
                </div>
            </form>
            </div>

            <a href="{% url 'profiles:my_profile_view' %}" class="item">
                 {{ request.user }}
            </a>

            <a href="{% url 'logout' %}" class="ui item">
                Logout
            </a>
        {% else %}
        <a href="{% url 'login' %}" class="ui item">
                Login
            </a>
        {% endif %}
    </div>
  </div>
</div>

templates/profile/profile_list.html
{% extends 'base.html' %}

{% block title %}Profile list{% endblock title%}

{% block content%}
    {% if is_empty %}
        <p>No profiles to view</p>
    {% endif %}
    {% for obj in object_list %}
        <div class="ui segment">
            <div class="ui grid">
                <div class="row">
                    <div class="three wide column">
                        <img class="ui small circular image" src={{obj.avatar.url}}>
                    </div>
                    <div class="thirteen wide column">
                        <h3>{{obj.user}}</h3>
                        <p>{{obj.bio}}</p>
                        <a href="{{obj.get_absolute_url}}"><button class="ui positive button mb-7, w_big">View my profile</button> </a>
                        <br>
                        <br>

                        {% if obj.user not in rel_receiver and obj.user not in rel_sender %}
                            <form action="{% url 'profiles:send-invite'%}" method="POST">
                                {% csrf_token%}
                                <input type="hidden" name="profile_pk" value="{{obj.pk}}">
                                <button class="ui positive basic button mb-7, w_big"><i class="plus square icon"></i> Add to friend list </button>
                            </form>
                        {% endif %}

                        {% if obj.user in rel_receiver and request.user not in obj.friends.all%}
                            <p><i class="user icon"></i>Waiting for approval</p>
                        {% endif %}

                    {% if request.user in obj.friends.all %}
                         <form action="{% url 'profiles:remove-friend'%}" method="POST">
                            {% csrf_token%}
                            <input type="hidden" name="profile_pk" value="{{obj.pk}}">
                                <button class="ui negative basic button mb-7, w_big" type="submit">
                                    <i class="minus square icon"></i> Remove from friend list
                                </button>
                        </form>
                      {% endif %}

                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
{% endblock content%}

templates/profile/to_invite_list.html
{% extends 'base.html' %}

{% block title %}Invite Friends{% endblock title%}

{% block content%}
<ul>
    {% for item in query %}
        <li>{{item}}</li>
    {% endfor %}
</ul>
{% endblock content%}